freq_base=60
ibrBus=[3, 6, 8] # Buses to place IBR generation at
GF=0.08  # % of Grid-forming inverters for nominal case
Gf=0.42 # % of Grid-following inverters for nominal case
resSize=1000  # Size of the reservoir
maxSimStep=1.0
trainSizes = [10:10:40;] # Number of times to sample the parameter space to calculate readout matrices
LB = [0.1, 0.1] # Lower-bounds on the 1) % of IBR at each node and 2) % of those IBR that are grid-forming
UB = [0.7, 0.5] # Upper-bounds on the 1) % of IBR at each node and 2) % of those IBR that are grid-forming
testSize=200 # Test size for benchmarking CTESN performance
tStop=70.0
tspan=(0.0, tStop)
interpolateStep=0.1
interpolateTime=0.0:interpolateStep:tStop
tripTime=10.0
testParams=[[0.6, 0.5], [0.6, 0.17], [0.3, 0.17]]
trainSamples = 15
paramSweepStep=0.01
settlingBand=0.000333